const val REFERENCE_COUNT = 100000
const val FRAME_COUNT = 10
const val PROCESS_PAGE_COUNT = 30
const val LOCALITY_BASE_CHANCE = 20
const val LOCALITY_GAIN = 2
const val LOCALITY_MINIMAL_SCOPE = 2
const val LOCALITY_MAXIMAL_SCOPE = 7
const val LOCALITY_MINIMAL_LENGTH = 2
const val LOCALITY_MAXIMAL_LENTH = 25
const val OPTIMAL_FUTURE_VISIBILITY = 200 // around 500 for most optimal results, 20 to be worse than LRU